# Generated by Django 2.2.3 on 2019-08-25 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_entrada', models.DateTimeField(verbose_name='Data de Entrada')),
                ('tipo_de_documento', models.CharField(max_length=30)),
                ('numero_do_documento', models.CharField(max_length=30)),
                ('assunto_do_documento', models.CharField(max_length=1000)),
                ('despacho_do_documento', models.CharField(max_length=200)),
                ('número_do_processo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Prazo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_prazo', models.CharField(max_length=20)),
                ('data_do_prazo', models.DateTimeField(verbose_name='Prazo')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inout.Documento')),
            ],
        ),
    ]
