# Generated by Django 2.2.3 on 2019-10-27 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_recebimento', models.DateTimeField(verbose_name='Data de Entrada')),
                ('tipo', models.IntegerField(choices=[(1, 'Carta'), (2, 'Convite'), (3, 'Documento'), (4, 'Email'), (5, 'Mandado de Intimação'), (6, 'Memorando'), (7, 'Memorando Circular'), (8, 'Movimentação da Solicitação'), (9, 'Notificação'), (10, 'Ofício'), (11, 'Ofício Circular'), (12, 'Requerimento'), (13, 'Outro')], default=10)),
                ('numero', models.CharField(max_length=30)),
                ('emissor', models.CharField(max_length=150)),
                ('assunto', models.CharField(max_length=1000)),
                ('despacho', models.CharField(max_length=200)),
                ('entrega_pessoal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Externo'), (2, 'Interno'), (3, 'USF')], default=2)),
                ('ano', models.DateTimeField(verbose_name='Ano do Livro')),
                ('volume', models.IntegerField(default=1)),
                ('encerrado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inout.Livro')),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.IntegerField(choices=[(1, 'AJUR'), (2, 'APOIO AO GABINETE'), (3, 'ASSCOM'), (4, 'ASSTEC'), (5, 'ATENDIMENTO'), (6, 'DAG'), (7, 'DASA'), (8, 'DCRA'), (9, 'DFUA'), (10, 'DGSIG'), (11, 'DLOS'), (12, 'GABINETE'), (13, 'INFORMATICA'), (14, 'OUVIDORIA'), (15, 'PROTOCOLO'), (16, 'RH'), (17, 'SAAG'), (18, 'SAFL'), (19, 'SAIPUA'), (20, 'SANBIO'), (21, 'SCALA'), (22, 'SDI'), (23, 'SGCT'), (24, 'SGFA'), (25, 'SGFU'), (26, 'SJPI'), (27, 'SLOPR'), (28, 'SLOPU'), (29, 'SLS'), (30, 'SPASO'), (31, 'SPATS'), (32, 'SPPUA'), (33, 'SZL'), (34, 'SZN'), (35, 'SZO'), (36, 'SZS'), (37, 'USF')])),
                ('ativo', models.BooleanField(default=True)),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inout.Orgao')),
            ],
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregue', models.BooleanField(default=False)),
                ('data_da_entrega', models.DateTimeField(null=True, verbose_name='Data da Entrega')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inout.Documento')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inout.Pagina')),
                ('recebido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inout.Setor')),
            ],
        ),
        migrations.CreateModel(
            name='Prazo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Audiência'), (2, 'Audiência Pública'), (3, 'Evento'), (4, 'Resposta'), (5, 'Reunião'), (6, 'Outro')], default=4)),
                ('vencimento', models.DateTimeField(verbose_name='Prazo')),
                ('encerrado', models.BooleanField(default=False)),
                ('dilacao', models.BooleanField(default=False)),
                ('quantidade_de_dilacoes', models.IntegerField(default=0)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inout.Documento')),
            ],
        ),
        migrations.AddField(
            model_name='livro',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inout.Setor'),
        ),
        migrations.AddField(
            model_name='documento',
            name='processo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inout.Processo'),
        ),
        migrations.AddField(
            model_name='documento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
