# Generated by Django 2.2.3 on 2019-11-12 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data_de_recebimento', models.DateField()),
                ('tipo', models.IntegerField()),
                ('numero', models.CharField(max_length=30)),
                ('emissor', models.CharField(max_length=50)),
                ('assunto', models.CharField(max_length=1000)),
                ('despacho', models.CharField(max_length=200)),
                ('entrega_pessoal', models.IntegerField()),
            ],
            options={
                'db_table': 'documento',
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('encerrado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'livro',
            },
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=10)),
                ('esfera', models.IntegerField()),
                ('municipio', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'orgao',
            },
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('fk_livro', models.ForeignKey(db_column='fk_livro', on_delete=django.db.models.deletion.DO_NOTHING, to='inout.Livro')),
            ],
            options={
                'db_table': 'pagina',
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=21)),
            ],
            options={
                'db_table': 'processo',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.IntegerField()),
                ('ativo', models.IntegerField()),
                ('fk_orgao', models.ForeignKey(db_column='fk_orgao', on_delete=django.db.models.deletion.DO_NOTHING, to='inout.Orgao')),
            ],
            options={
                'db_table': 'setor',
            },
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('entregue', models.IntegerField()),
                ('data_da_entrega', models.DateField(blank=True, null=True)),
                ('fk_documento', models.ForeignKey(db_column='fk_documento', on_delete=django.db.models.deletion.DO_NOTHING, to='inout.Documento')),
                ('fk_pagina', models.ForeignKey(db_column='fk_pagina', on_delete=django.db.models.deletion.DO_NOTHING, to='inout.Pagina')),
                ('fk_setor_destino', models.ForeignKey(db_column='fk_setor_destino', on_delete=django.db.models.deletion.DO_NOTHING, related_name='setor_de_destino', to='inout.Setor')),
                ('fk_setor_origem', models.ForeignKey(db_column='fk_setor_origem', on_delete=django.db.models.deletion.DO_NOTHING, related_name='setor_de_origem', to='inout.Setor')),
            ],
            options={
                'db_table': 'protocolo',
            },
        ),
        migrations.CreateModel(
            name='Prazo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField()),
                ('vencimento', models.DateTimeField()),
                ('encerrado', models.IntegerField()),
                ('dilacao', models.IntegerField()),
                ('quantidade_de_dilacoes', models.IntegerField(blank=True, null=True)),
                ('fk_documento', models.ForeignKey(db_column='fk_documento', on_delete=django.db.models.deletion.DO_NOTHING, to='inout.Documento')),
            ],
            options={
                'db_table': 'prazo',
            },
        ),
        migrations.CreateModel(
            name='Lotacao',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cargo', models.IntegerField()),
                ('entrada', models.DateField()),
                ('saida', models.DateField(blank=True, null=True)),
                ('fk_setor', models.ForeignKey(db_column='fk_setor', on_delete=django.db.models.deletion.DO_NOTHING, to='inout.Setor')),
                ('fk_user', models.ForeignKey(db_column='fk_user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lotacao',
            },
        ),
        migrations.AddField(
            model_name='livro',
            name='fk_setor',
            field=models.ForeignKey(db_column='fk_setor', on_delete=django.db.models.deletion.DO_NOTHING, to='inout.Setor'),
        ),
        migrations.AddField(
            model_name='documento',
            name='fk_processo',
            field=models.ForeignKey(blank=True, db_column='fk_processo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inout.Processo'),
        ),
        migrations.AddField(
            model_name='documento',
            name='fk_user',
            field=models.ForeignKey(db_column='fk_user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
