# Generated by Django 2.2.3 on 2019-11-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='pdf',
            field=models.TextField(blank=True, null=True),
        ),
    ]
