# Generated by Django 2.2.3 on 2019-11-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='processo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
