# Generated by Django 2.2.3 on 2019-11-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
