# Generated by Django 2.2.3 on 2019-10-28 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocolo',
            name='recebido_por',
        ),
        migrations.AddField(
            model_name='protocolo',
            name='setor_destino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='setor_de_destino', to='inout.Setor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protocolo',
            name='setor_origem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='setor_de_origem', to='inout.Setor'),
            preserve_default=False,
        ),
    ]
