# Generated by Django 2.2.3 on 2019-11-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0002_auto_20191129_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
    ]
