# Generated by Django 2.2.3 on 2019-11-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0002_auto_20191112_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prazo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
