# Generated by Django 2.2.3 on 2019-08-27 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0002_documento_orgao_expedidor_do_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='número_do_processo',
            new_name='numero_do_processo',
        ),
    ]
