# Generated by Django 2.2.5 on 2019-11-06 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inout', '0002_auto_20191027_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgao',
            name='sigla',
            field=models.CharField(default='teste', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero',
            field=models.CharField(max_length=21),
        ),
        migrations.CreateModel(
            name='Lotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.IntegerField(choices=[(1, 'Arquiteto'), (2, 'Assistente Administrativo'), (3, 'Chefe de Gabinete'), (4, 'Diretor'), (5, 'Estagiário'), (6, 'Fiscal'), (7, 'Recepcionista'), (8, 'Secretário'), (9, 'Técnico em Informática')])),
                ('entrada', models.DateTimeField(verbose_name='Data de entrada na função')),
                ('saida', models.DateTimeField(verbose_name='Data de saída da função')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inout.Setor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
