# Generated by Django 2.2.3 on 2019-11-24 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0002_auto_20191124_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=32)),
                ('first_name', models.CharField(blank=True, max_length=15, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('grupo', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AlterField(
            model_name='documento',
            name='entrega_pessoal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fk_user',
            field=models.ForeignKey(db_column='fk_user', on_delete=django.db.models.deletion.DO_NOTHING, to='inout.User'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='livro',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='tipo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lotacao',
            name='cargo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lotacao',
            name='fk_user',
            field=models.ForeignKey(db_column='fk_user', on_delete=django.db.models.deletion.DO_NOTHING, to='inout.User'),
        ),
        migrations.AlterField(
            model_name='lotacao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='ativo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='esfera',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='estado',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prazo',
            name='dilacao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='prazo',
            name='encerrado',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='prazo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='ativo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='setor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
