# Generated by Django 2.2.5 on 2019-11-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0003_auto_20191106_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgao',
            name='esfera',
            field=models.IntegerField(choices=[(1, 'Estadual'), (2, 'Federal'), (3, 'Municipal')], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orgao',
            name='municipio',
            field=models.CharField(default='Natal', max_length=32),
            preserve_default=False,
        ),
    ]
