# Generated by Django 2.2.3 on 2019-11-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0003_auto_20191129_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prazo',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Audiência'), (2, 'Evento'), (3, 'Fiscalização'), (4, 'Palestra'), (5, 'Resposta'), (6, 'Reunião'), (7, 'Vistoria')], default=5),
        ),
    ]
