# Generated by Django 2.2.3 on 2019-11-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0004_auto_20191124_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgao',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
