# Generated by Django 2.2.3 on 2019-09-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0004_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='prazo',
            name='status_do_prazo',
            field=models.IntegerField(default=0),
        ),
    ]
