# Generated by Django 2.2.3 on 2019-11-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0004_auto_20191112_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prazo',
            name='dilacao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
