# Generated by Django 2.2.3 on 2019-09-22 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0005_prazo_status_do_prazo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prazo',
            name='status_do_prazo',
        ),
    ]
