# Generated by Django 2.2.3 on 2019-11-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0005_auto_20191124_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Carta'), (2, 'Convite'), (3, 'Documento'), (4, 'Email'), (5, 'Mandado de Intimação'), (6, 'Memorando'), (7, 'Memorando Circular'), (8, 'Movimentação da Solicitação'), (9, 'Notificação'), (10, 'Ofício'), (11, 'Ofício Circular'), (12, 'Requerimento'), (13, 'Outro')], default=10),
        ),
        migrations.AlterField(
            model_name='livro',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Externo'), (2, 'Interno'), (3, 'USF')], default=2),
        ),
        migrations.AlterField(
            model_name='lotacao',
            name='cargo',
            field=models.IntegerField(choices=[(1, 'Arquiteto'), (2, 'Assistente Administrativo'), (3, 'Chefe de Gabinete'), (4, 'Diretor'), (5, 'Estagiário'), (6, 'Fiscal'), (7, 'Recepcionista'), (8, 'Secretário'), (9, 'Técnico em Informática')]),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='ativo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='esfera',
            field=models.IntegerField(choices=[(1, 'Estadual'), (2, 'Federal'), (3, 'Municipal')]),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Acre (AC)'), (2, 'Alagoas (AL)'), (3, 'Amapá (AP)'), (4, 'Amazonas (AM)'), (5, 'Bahia (BA)'), (6, 'Ceará (CE)'), (7, 'Distrito Federal (DF)'), (8, 'Espírito Santo (ES)'), (9, 'Goiás (GO)'), (10, 'Maranhão (MA)'), (11, 'Mato Grosso (MT)'), (12, 'Mato Grosso do Sul (MS)'), (13, 'Minas Gerais (MG)'), (14, 'Pará (PA)'), (15, 'Paraíba (PB)'), (16, 'Paraná (PR)'), (17, 'Pernambuco (PE)'), (18, 'Piauí (PI)'), (19, 'Rio de Janeiro (RJ)'), (20, 'Rio Grande do Norte (RN)'), (21, 'Rio Grande do Sul (RS)'), (22, 'Rondônia (RO)'), (23, 'Roraima (RR)'), (24, 'Santa Catarina (SC)'), (25, 'São Paulo (SP)'), (26, 'Sergipe (SE)'), (27, 'Tocantins (TO)')], default=20),
        ),
    ]
