# Generated by Django 2.2.6 on 2019-11-07 18:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0006_auto_20191107_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotacao',
            name='entrada',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 7, 18, 57, 4, 216618, tzinfo=utc), verbose_name='Data de entrada na função'),
        ),
        migrations.AlterField(
            model_name='lotacao',
            name='saida',
            field=models.DateTimeField(null=True, verbose_name='Data de saída da função'),
        ),
    ]
