# Generated by Django 2.2.3 on 2019-11-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0006_auto_20191113_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgao',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
