# Generated by Django 2.2.3 on 2019-11-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0007_auto_20191124_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='entrega_pessoal',
            field=models.BooleanField(),
        ),
    ]
