# Generated by Django 2.2.5 on 2019-09-30 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0007_prazo_prazo_encerrado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
