# Generated by Django 2.2.3 on 2019-11-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0007_auto_20191107_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotacao',
            name='entrada',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de entrada na função'),
        ),
    ]
