# Generated by Django 2.2.3 on 2019-10-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0010_auto_20191017_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='entrega_pessoal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livro',
            name='encerrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prazo',
            name='dilacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prazo',
            name='quantidade_de_dilacoes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='data_da_entrega',
            field=models.DateTimeField(null=True, verbose_name='Data da Entrega'),
        ),
        migrations.AddField(
            model_name='setor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Carta'), (2, 'Convite'), (3, 'Documento'), (4, 'Email'), (5, 'Mandado de Intimação'), (6, 'Memorando'), (7, 'Memorando Circular'), (8, 'Movimentação da Solicitação'), (9, 'Notificação'), (10, 'Ofício'), (11, 'Ofício Circular'), (12, 'Requerimento'), (13, 'Outro')], default=9),
        ),
        migrations.AlterField(
            model_name='livro',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Interno'), (2, 'Externo'), (3, 'USF')], default=1),
        ),
        migrations.AlterField(
            model_name='prazo',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Audiência'), (2, 'Audiência Pública'), (3, 'Evento'), (4, 'Resposta'), (5, 'Reunião'), (6, 'Outro')], default=4),
        ),
        migrations.AlterField(
            model_name='setor',
            name='nome',
            field=models.IntegerField(choices=[(1, 'AJUR'), (2, 'APOIO AO GABINETE'), (3, 'ASSCOM'), (4, 'ASSTEC'), (5, 'ATENDIMENTO'), (6, 'DAG'), (7, 'DASA'), (8, 'DCRA'), (9, 'DFUA'), (10, 'DGSIG'), (11, 'DLOS'), (12, 'GABINETE'), (13, 'INFORMATICA'), (14, 'OUVIDORIA'), (15, 'PROTOCOLO'), (16, 'RH'), (17, 'SAAG'), (18, 'SAFL'), (19, 'SAIPUA'), (20, 'SANBIO'), (21, 'SCALA'), (22, 'SDI'), (23, 'SGCT'), (24, 'SGFA'), (25, 'SGFU'), (26, 'SJPI'), (27, 'SLOPR'), (28, 'SLOPU'), (29, 'SLS'), (30, 'SPASO'), (31, 'SPATS'), (32, 'SPPUA'), (33, 'SZL'), (34, 'SZN'), (35, 'SZO'), (36, 'SZS'), (37, 'USF')]),
        ),
    ]
